exam/App/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from App import views

urlpatterns = [
    path('home/', views.index, name='index'),
    path('home/<slug:name>/', views.get_name, name='name'),
    path('redirect/', views.http_redirect, name='red'),
    re_path(r'^tel/(\d{4}-\d{8})/$', views.tel, name='tel'),
]

exam/App02/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from App02 import views

app_name = 'App02'

urlpatterns = [
    path('home/', views.index, name='index'),
    path('filter/', views.fil, name='filter'),
    path('register/', views.register, name='register'),
    path('url/', views.include_url, name='url'),
    path('data/', views.handle_data, name='data'),
    path('search/', views.search, name='search'),
    path('send/', views.send, name='send'),
    path('page/', views.show_page, name='page'),
    path('page/<int:page_num>', views.show_page, name='page'),
    path('login/',views.login,name='login'),

]

exam/exam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('App.urls')),
    path('app02/', include('App02.urls')),
]

exam/App/models.py
from django.db import models


# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)

    class Meta:
        db_table = 'users'

exam/App02/models.py
from django.db import models


# Create your models here.
class User(models.Model):
    uid = models.AutoField(primary_key=True)
    username = models.CharField(max_length=30, unique=True)
    password = models.CharField(max_length=20)
    regtime = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'user'
        ordering = ['regtime']

exam/App/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse

from App.models import User


def index(request):
    users = User.objects.all()
    return render(request, 'index.html', context={'title': 'django', 'name': '用戶', 'users': users})
    # return HttpResponse('首頁')


def get_name(request, name):
    print(request.GET)
    print(request.GET.getlist('age'))
    return HttpResponse(name)


def http_redirect(request):
    return redirect(reverse('tel', args=('1234-56795978',)))


def tel(request, phone):
    return HttpResponse(phone)

exam/App02/views.py
from datetime import datetime
from random import randint

from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from App02.models import User


def index(request):
    users = [{'username': 'pein'}, {'username': 'niku'}]
    return render(request, 'app02/index.html', context=locals())


def fil(request):
    num = 9
    var = None
    t1 = datetime.now()
    return render(request, 'test.html', context=locals())


def register(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(username, password)
    return render(request, 'app02/register.html')


def include_url(request):
    return render(request, 'app02/menu.html')


def handle_data(request):
    # user = User(username='pein', password='150620')
    # user.save()
    # User.objects.create(username='ert',password='12345678')
    # User.objects.bulk_create([User(username='ad1', password='pw1'), User(username='ad2', password='pw2')])

    # user1 = User.objects.get(pk=5)
    # user.password = 'abcd1234'
    # user.save()
    # users = User.objects.filter(uid__gte=1)
    # print(users)
    # users.delete()
    # print(user, type(user))
    # if user:
    #     user.delete()

    first_name = ['王', '李', '张', '刘', '陈', '杨', '黄', '赵', '吴', '周']
    last_name = ['俊豪', '婉如', '嘉美', '子轩', '志妍', '山勇', '秀法']
    users = []
    for first in first_name:
        for last in last_name:
            name = first + last
            users.append(User(username=name, password=randint(11111111, 99999999)))

    User.objects.bulk_create(users)

    return HttpResponse('数据添加完毕')


def search(request):
    # data = User.objects.all()
    # data = User.objects.filter(uid__gt=40).filter(uid__lt=50)
    # data = User.objects.order_by('uid')[20:30]
    # data = User.objects.filter(username__startswith='张')

    # from django.db.models import Max,Min,Sum,Avg
    # uid = User.objects.aggregate(
    #
    #
    # Max('uid'))
    # print(uid)
    # return HttpResponse('分组排序')

    data = User.objects.filter(Q(uid__lte=12) | Q(uid__gte=70))
    return render(request, 'app02/list.html', locals())


def send(request):
    from App02.sms import send_sms
    mobile = "18981200020"
    text = "您的验证码是：121254。请不要把验证码泄露给其他人。"
    print(send_sms(text, mobile))
    return HttpResponse('发送成功')


def show_page(request,page_num=1):
    users = User.objects.all()
    paginator = Paginator(users,10)
    pages = paginator.page(page_num)
    last_page = -paginator.num_pages
    print(last_page)
    return render(request, 'app02/page.html',locals())

exam/App02/templates/test.html
{% load my_tag %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>{{ num|sub }}</p>
</body>
</html>

exam/templates/app02/filter.html
{% load my_tag %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>{{ num|add:'1' }}</p>
<p>{{ var|default_if_none:'不存在' }}</p>
<p>{{ as|default:'就没有' }}</p>
<p>
    {{ t1|date:'Y-m-d H:i:s' }}
</p>
<p>{{ num|sub }}</p>
</body>
</html>

exam/templates/app02/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
<table border="1" >
    {% for user in users %}
    <tr>
    <td>{{ user.username }}</td>
    </tr>
    {% endfor %}

</table>
</body>
</html>

exam/templates/app02/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>查询结果</title>
</head>
<body>
{% for user in data %}
    <li>{{ user.username }} ---- {{ user.password }}</li>
{% endfor %}

</body>
</html>

exam/templates/app02/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>菜单</title>
</head>
<body>
<li><a href="{% url 'App02:index' %}">首页</a></li>
<li><a href="{% url 'App02:register' %}">注册</a></li>
</body>
</html>

exam/templates/app02/page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>分页</title>
</head>
<body>
<table border="1" cellpadding="10">
    <th>用户名</th>
    <th>密码</th>
    {% for user in pages.object_list %}
    <tr>
    <td>{{ user.username }}</td>
    <td>{{ user.password }}</td>
    </tr>
    {% endfor %}
</table>
<div>
    {% if page_num|add:'-1' %}
    <a href="{% url 'App02:page' page_num=page_num|add:'-1'%}">上一页</a>
        {% else %}
        <a href="{% url 'App02:page' page_num=page_num%}">上一页</a>
    {% endif %}

    {% for page in paginator.page_range %}
        <a href="{% url 'App02:page' page_num=page%}">{{ page }}</a>
    {% endfor %}
    {% if page_num|add:last_page %}
    <a href="{% url 'App02:page' page_num=page_num|add:'1'%}">下一页</a>
        {% else %}
        <a href="{% url 'App02:page' page_num=page_num%}">下一页</a>
    {% endif %}
</div>

</body>
</html>

exam/templates/app02/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
     用户名：<input type="text" name="username"> <br>
     密码：  <input type="text" name="password"> <br>
     <input type="submit" value="提交">
</form>
</body>
</html>

exam/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
<p>
    Hello,{{ name }}
</p>
<p>
    {% for user in users %}
    <li>{{ user.username }}: {{ user.password }}</li>
    {% endfor %}

</p>
</body>
</html>